### ISSUE TITLE
Question: TD(0) Actor-Critic

### ISSUE THREAD

**Issue by koki0702** [chengxi600/RLStuff#1]
According to Sutton's book, the pseudo code for actor-critic is written as follows.

<img width="1052" alt="image" src="https://user-images.githubusercontent.com/515809/153786118-0a0978da-9048-468a-800f-593f5c28aa57.png">

Do you know why the `I` is introduced here?
As far as I could find in the book, I could not find any explanation for this.

Your code: 
https://github.com/chengxi600/RLStuff/blob/master/Actor-Critic/Actor-Critic_TD_0.ipynb

**Comment by chengxi600** [comment]
While I'm not entirely sure either, I believe it's just an extra parameter so the step size is adaptive.
